on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

  release-artifact:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Package jar
        run: |
          mvn dependency:resolve dependency:resolve-plugins
          mvn package
          mv target/expense.tracker-1.0.0.jar target/expense.tracker.jar
      - name: Upload jar
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} target/expense.tracker.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-images:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t expense-tracker:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }} .
          docker build -f Dockerfile -t expense-tracker:latest .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Tag images
        run: |
          docker tag expense-tracker:${{needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }} ghcr.io/sarahpijoos/expense-tracker:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker tag expense-tracker:latest ghcr.io/sarahpijoos/expense-tracker:latest
      - name: Push images
        run: |
          docker push ghcr.io/sarahpijoos/expense-tracker:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker push ghcr.io/sarahpijoos/expense-tracker:latest